### ISSUE TITLE
makeathon-2: schedule main content

### ISSUE THREAD

**Issue by shawnpradeep** [ugaHacks/ugahacks#208]
includes:

- heading
- tenative schedule (for now, feel free to fill it in with placeholders for each column of what, when, and where)
- schedule is supposed to pan left, and vanish revealing the day 2 schedule

figma: https://www.figma.com/file/lAflsEL32FYluDAg9fms2a/make9.ugahacks.com-(Copy)?type=design&node-id=0%3A1&mode=design&t=EttjSYNlGciVcosu-1

**Comment by nikita-jha** [comment]
Finished adding all the components
