### ISSUE TITLE
navbar and home

### ISSUE THREAD

**Issue by vansharora03** [ugaHacks/ugahacks#293]

**Comment by TheRyanMajd** [comment]
Check branch [features/navbar](https://github.com/ugahacks/ugahacks/commit/33c47b26d256b5970b2c11a910523467493de3db) 

I committed some changes and did part of the home. In the commit message, I mentioned what I have left:
Added social logos
Updated Splash Screen
Fixed styling for page
Added Navbar (responsive) // not linked
* Need to add fonts
* Purposely made MLH Banner half sized
* Missing red star

**Comment by TheRyanMajd** [comment]
Added red star and fonts, it's done! I need you to take a look at it before I submit a PR pls :D @vansharora03 
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/4a8bf9e8-625c-4ceb-99be-456bf5546f41">
